### ISSUE TITLE
Guzzle/http uses guzzle/common which is abandoned

### ISSUE THREAD

**Issue by ArlingtonHouse** [Geocodio/geocodio-php#10]
I'm not too familiar with Guzzle but it looks like the Guzzle/http dependency uses Guzzle/common which is abandoned in favor of guzzle/guzzle.  So we'd need to update the composer line for guzzle/http to 

"guzzlehttp/guzzle": "5.*"

But I'm not sure if this will require code changes in the project.

**Comment by leigeber** [comment]
Just noticed the same thing. Guzzle 6 is also available now as well.

**Comment by MiniCodeMonkey** [comment]
Thanks for reporting this. We'll get it updated shortly.

**Comment by tomschlick** [comment]
Has anyone touched this yet? I have some free time later and could take a stab at starting a PR for it...

**Comment by MiniCodeMonkey** [comment]
We have now upgraded to Guzzle 6 with v1.3.0
