### ISSUE TITLE
Guzzle request error handling issues

### ISSUE THREAD

**Issue by patrickcarlohickman** [Geocodio/geocodio-php#19]
There are a couple issues with the Guzzle request error handling in the Client. 

First, without setting the `http_errors` request option to `false`, Guzzle will throw exceptions when 4xx/5xx responses are returned. Since this request option is not set, and the Guzzle requests are not wrapped in try/catch blocks, this exception will be thrown and the `checkResponse` method won't ever be called for 4xx/5xx responses.

Second, Guzzle will throw exceptions for networking issues (timeouts, dns issues, network failures). These exceptions aren't governed by an option, so they must always be taken into account.

I didn't submit a PR for any of this, as I didn't know what direction you wanted to go.

Thanks,
Patrick

**Comment by MiniCodeMonkey** [comment]
This has been resolved now with the release of v1.9.0
